# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/client"
      - "/db"
      - "/hma"
      - "/nodejs-instrumentation"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  # Enable version updates for npm
  # Cover / directory dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      root-prod-security:
        dependency-type: 'production'
        applies-to: 'security-updates'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      root-prod:
        dependency-type: 'production'
        applies-to: 'version-updates'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      root-dev:
        dependency-type: 'development'
        applies-to: 'version-updates'
        patterns:
          - '*'

  # Cover /db directory dependencies
  - package-ecosystem: 'npm'
    directory: '/db'
    schedule:
      interval: 'weekly'
    groups:
      db-prod-security:
        dependency-type: 'production'
        applies-to: 'security-updates'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/db'
    schedule:
      interval: 'weekly'
    groups:
      db-prod:
        dependency-type: 'production'
        applies-to: 'version-updates'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/db'
    schedule:
      interval: 'weekly'
    groups:
      db-dev:
        dependency-type: 'development'
        applies-to: 'version-updates'
        patterns:
          - '*'

  # Cover /migrator directory dependencies
  - package-ecosystem: 'npm'
    directory: '/migrator'
    schedule:
      interval: 'weekly'
    groups:
      migrator-prod-security:
        dependency-type: 'production'
        applies-to: 'security-updates'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/migrator'
    schedule:
      interval: 'weekly'
    groups:
      migrator-prod:
        dependency-type: 'production'
        applies-to: 'version-updates'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/migrator'
    schedule:
      interval: 'weekly'
    groups:
      migrator-dev:
        dependency-type: 'development'
        applies-to: 'version-updates'
        patterns:
          - '*'

  # Cover /server directory dependencies
  - package-ecosystem: 'npm'
    directory: '/server'
    schedule:
      interval: 'weekly'
    groups:
      server-prod-security:
        dependency-type: 'production'
        applies-to: 'security-updates'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/server'
    schedule:
      interval: 'weekly'
    groups:
      server-prod:
        dependency-type: 'production'
        applies-to: 'version-updates'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/server'
    schedule:
      interval: 'weekly'
    groups:
      server-dev:
        dependency-type: 'development'
        applies-to: 'version-updates'
        patterns:
          - '*'

  # Cover /client directory dependencies
  - package-ecosystem: 'npm'
    directory: '/client'
    schedule:
      interval: 'weekly'
    groups:
      client-prod-security:
        dependency-type: 'production'
        applies-to: 'security-updates'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/client'
    schedule:
      interval: 'weekly'
    groups:
      client-prod:
        dependency-type: 'production'
        applies-to: 'version-updates'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/client'
    schedule:
      interval: 'weekly'
    groups:
      client-dev:
        dependency-type: 'development'
        applies-to: 'version-updates'
        patterns:
          - '*'

  # Cover /nodejs-instrumentation directory dependencies
  - package-ecosystem: 'npm'
    directory: '/nodejs-instrumentation'
    schedule:
      interval: 'weekly'
    groups:
      nodejs-instrumentation-prod-security:
        dependency-type: 'production'
        applies-to: 'security-updates'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/nodejs-instrumentation'
    schedule:
      interval: 'weekly'
    groups:
      nodejs-instrumentation-prod:
        dependency-type: 'production'
        applies-to: 'version-updates'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/nodejs-instrumentation'
    schedule:
      interval: 'weekly'
    groups:
      nodejs-instrumentation-dev:
        dependency-type: 'development'
        applies-to: 'version-updates'
        patterns:
          - '*'
